### ISSUE TITLE
TypeError: argument of type 'WindowsPath' is not iterable

### ISSUE THREAD

**Issue by dip16gphy** [paudetseis/RfPy#33]
While using `rfpy_ccp PBA.pkl --start=92.74,11.66 --end=92.75,11.65 --snr=10 --snrh=5 --no-outlier --load --prep --prestack --ccp --gccp --linear --figure` , I am getting this error. 

Traceback (most recent call last):
  File "c:\users\uplc\anaconda3\envs\rfpy\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\uplc\anaconda3\envs\rfpy\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\UPLC\anaconda3\envs\rfpy\Scripts\rfpy_ccp.exe\__main__.py", line 7, in <module>
  File "c:\users\uplc\anaconda3\envs\rfpy\lib\site-packages\rfpy\scripts\rfpy_ccp.py", line 623, in main
    ccpimage.save(prep_file)
  File "c:\users\uplc\anaconda3\envs\rfpy\lib\site-packages\rfpy\ccp.py", line 637, in save
    if not ".pkl" in title:
**TypeError: argument of type 'WindowsPath' is not iterable** 

However, the message also shows this before throwing error:
![image](https://user-images.githubusercontent.com/101346054/161367338-7921be91-b393-4bc6-a7c1-6d4083efbcbc.png)

**Comment by wsja** [comment]
This should be fixed in the current master branch. Can you please test it and see if it resolved your issue?

**Comment by dip16gphy** [comment]
> rfpy_ccp PBA.pkl --start=92.74,11.66 --end=92.75,11.65 --snr=10 --snrh=5 --no-outlier --load --prep --prestack --ccp --gccp --linear --figure

Again it throws the same error as above.

**Comment by wsja** [comment]
Please have a look at the updated version and let me know if the issue persists.

**Comment by dip16gphy** [comment]
> Please have a look at the updated version and let me know if the issue persists.



nothing changes!! Again same error

**Comment by wsja** [comment]
The problem is not obvious to me. Can you please copy+paste the entire Traceback here?

**Comment by wsja** [comment]
The problem is not obvious to me. Can you please copy+paste the entire Traceback here?

**Comment by dip16gphy** [comment]
> Traceback (most recent call last):
> File "c:\users\uplc\anaconda3\envs\rfpy\lib\runpy.py", line 194, in _run_module_as_main
> return _run_code(code, main_globals, None,
> File "c:\users\uplc\anaconda3\envs\rfpy\lib\runpy.py", line 87, in _run_code exec(code, run_globals) File "C:\Users\UPLC\anaconda3\envs\rfpy\Scripts\rfpy_ccp.exe__main__.py", line 7, in
> File "c:\users\uplc\anaconda3\envs\rfpy\lib\site-packages\rfpy\scripts\rfpy_ccp.py", line 623, in main
> ccpimage.save(prep_file)
> File "c:\users\uplc\anaconda3\envs\rfpy\lib\site-packages\rfpy\ccp.py", line 637, in save
> if not ".pkl" in title:
> **TypeError: argument of type 'WindowsPath' is not iterable**

Traceback (most recent call last):
File "c:\users\uplc\anaconda3\envs\rfpy\lib\runpy.py", line 194, in _run_module_as_main
return _run_code(code, main_globals, None,
File "c:\users\uplc\anaconda3\envs\rfpy\lib\runpy.py", line 87, in run_code
exec(code, run_globals)
File "C:\Users\UPLC\anaconda3\envs\rfpy\Scripts\rfpy_ccp.exe_main.py", line 7, in
File "c:\users\uplc\anaconda3\envs\rfpy\lib\site-packages\rfpy\scripts\rfpy_ccp.py", line 623, in main
ccpimage.save(prep_file)
File "c:\users\uplc\anaconda3\envs\rfpy\lib\site-packages\rfpy\ccp.py", line 637, in save
if not ".pkl" in title:
TypeError: argument of type 'WindowsPath' is not iterable

**Comment by wsja** [comment]
It looks like you are still using the former version of `RfPy`. The line in question has now moved to 638, instead of 637, where your error is occurring. This suggests that in the code you are using line 633 does not contain the most recent fix `title = str(title)`.

Please try downloading the most recent `RfPy` version and re-installing it.
