### ISSUE TITLE
ValueError: could not broadcast input array from shape (724,) into shape (725,)

### ISSUE THREAD

**Issue by dip16gphy** [paudetseis/RfPy#35]
While running the command for gaussian filter with 'rfpy_recalc' script, it throws following error:

Traceback (most recent call last):
  File "c:\users\uplc\anaconda3\envs\rfpy\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\uplc\anaconda3\envs\rfpy\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\UPLC\anaconda3\envs\rfpy\Scripts\rfpy_recalc.exe\__main__.py", line 7, in <module>
  File "c:\users\uplc\anaconda3\envs\rfpy\lib\site-packages\rfpy\scripts\rfpy_recalc.py", line 377, in main
    rfdata.deconvolve(
  File "c:\users\uplc\anaconda3\envs\rfpy\lib\site-packages\rfpy\rfdata.py", line 851, in deconvolve
    rfL, rfQ, rfT = _decon(trL, trQ, trT, trNl, nn, method)
  File "c:\users\uplc\anaconda3\envs\rfpy\lib\site-packages\rfpy\rfdata.py", line 752, in _decon
    gauss = _gauss_filt(dt, npad, gfilt)
  File "c:\users\uplc\anaconda3\envs\rfpy\lib\site-packages\rfpy\rfdata.py", line 669, in _gauss_filt
    gauss[nft21:] = np.flip(gauss[1:nft21-1])
**ValueError: could not broadcast input array from shape (724,) into shape (725,)**

**Comment by wsja** [comment]
The gauss filter is currently unmaintained. Please remove the option `--gfilt=1.` for the time being.
