### ISSUE TITLE
IndexError: list index out of range when computing the BAZ panel

### ISSUE THREAD

**Issue by Qian-Zhou3** [paudetseis/RfPy#37]
Hi Pascal!

I was following the given tutorial to compute PRF, I was able to get results until Back-azimuth panel.
My command was the following:

rfpy_plot.py --no-outlier --bp=0.05,0.5 --nbaz=36 --normalize --trange=-2.,30. MMPY.pkl 

The error is in the plot script.

Traceback (most recent call last):
  File "/home/qian/anaconda3/envs/rfpy/bin/rfpy_plot.py", line 588, in <module>
    main()
  File "/home/qianl/anaconda3/envs/rfpy/bin/rfpy_plot.py", line 523, in main
    for tr in rf_tmp[0]:
IndexError: list index out of range

Do you know what should be the problem? Let me know if you require more information

I have other question.
I plan to apply PRF for two networks, one with short-period instruments (1 s corner frequency) and 
other with broad -band sensors (30 s corner frequency).

Do you think that it is best to process them separately? For example band-passing the short period seismograms from 0.5 Hz to let's say 1.5 Hz and do the same for the  broad-band seismograms ?
Or is it better to process them using the same band-pass filter for both networks? lets say a adjust to a more or less common frequency between 0.05  Hz to  1.5 Hz  

Thanks in advance!

**Comment by Qian-Zhou3** [comment]
I found my mistake! Now it is running perfectly.
Do you know how to use it with restricted stations?

Thanks in advance!

**Comment by LevCarlo** [comment]
> I found my mistake! Now it is running perfectly. Do you know how to use it with restricted stations?
> 
> Thanks in advance!

Can you share how to solve it ?

**Comment by paudetseis** [comment]
Hi @Qian-Zhou3, Thank you for reporting the issue and for fixing it. I apologize that I wasn't able to help you earlier. I suspect your error arose because you didn't have any RFs that passed the QC thresholds that you set. Is this correct? Please share how you solved this problem.

Regarding the restricted stations, do you mean those requiring a username and password on IRIS (or another FDSN client)? In that case, you can simply specify these fields as an argument when calling the scripts - see the documentation:
```
-U USERAUTH, --User-Auth USERAUTH
                        Enter your IRIS Authentification Username and Password
                        (--User-Auth='username:authpassword') to access and
                        download restricted data. [Default no user and
                        password]
```
