### ISSUE TITLE
rfpy_plot error list out of range

### ISSUE THREAD

**Issue by IADKA** [paudetseis/RfPy#38]
when i try to plot after rfpy_calc, this error shown:
Traceback (most recent call last):
  File "C:\Users\andre\anaconda3\envs\rfpy\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\andre\anaconda3\envs\rfpy\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\andre\anaconda3\envs\rfpy\Scripts\rfpy_plot.exe\__main__.py", line 7, in <module>
  File "C:\Users\andre\anaconda3\envs\rfpy\lib\site-packages\rfpy\scripts\rfpy_plot.py", line 523, in main
    for tr in rf_tmp[0]:
IndexError: list index out of range

**Comment by raghav413** [comment]
is the problem solved? if yes please write the solution here. thanks

**Comment by paudetseis** [comment]
This has been fixed in version >= 0.2.0
